default: &default
  address:              smtp.gmail.com
  port:                 587
  domain:               heroku.com
  user_name:            sarriagada87@gmail.com
  password:             yosoymuyfeliz
  authentication:       plain
  enable_starttls_auto: true

development:
  <<: *default

production:
  <<: *default